### ISSUE TITLE
IntegrationExamples ERROR

### ISSUE THREAD

**Issue by dotrungkien3210** [IABTechLab/uid2-client-java#39]
Hi,
i was test in class IntegrationExamples, but when call refresh function, it return 401 error, i can't find where i'm wrong, can you give me some ideal

**Comment by dotrungkien3210** [comment]
V2Request request = makeV2Request(Instant.now());
            URL serviceUrl = new URL(endpoint + "/v2/key/sharing");
            URLConnection conn = serviceUrl.openConnection();
            HttpURLConnection httpsConnection = (HttpURLConnection) conn;
            httpsConnection.setRequestMethod("POST");
            httpsConnection.setDoInput(true);
            httpsConnection.setDoOutput(true);
            httpsConnection.setRequestProperty("Authorization", "Bearer " + this.authKey);
            httpsConnection.setRequestProperty("X-UID2-Client-Version", "java-" + PublisherUid2Helper.getArtifactAndVersion());

            try(OutputStream os = httpsConnection.getOutputStream()) {
                os.write(request.envelope);
            }
in this function, i had change endpoint and authKey value, 


    private V2Request makeV2Request(Instant now) {
        byte[] nonce = new byte[8];
        new SecureRandom().nextBytes(nonce);
        ByteBuffer writer = ByteBuffer.allocate(16);
        writer.putLong(now.toEpochMilli());
        writer.put(nonce);
        byte[] encrypted = Uid2Encryption.encryptGCM(writer.array(), null, this.secretKey);
        ByteBuffer request = ByteBuffer.allocate(encrypted.length + 1);
        request.put((byte)1); // version
        request.put(encrypted);
        return new V2Request(Base64.getEncoder().encode(request.array()), nonce);
    }
in this function i had change secretKey value

is it enough

**Comment by sunnywu** [comment]
Hi sorry we missed your message here. If you are still stuck, could you contact the TTD TAM team who is providing the support. Most likely either your API key or the secret value you used to encrypt the request was invalid.

Let me know if you have further questions. Thanks

**Comment by sunnywu** [comment]
Hi @dotrungkien3210 I will close this issue for now but if you have any further feedback please reply and we can follow up. Thanks
