### ISSUE TITLE
Check encryption and decryption

### ISSUE THREAD

**Issue by dotrungkien3210** [IABTechLab/uid2-client-java#40]
Hello,
when i run token generate and refresh, it successfully create UID2 token for user, but how i can check that token for that user is right or wrong, i can't find funtion to decryption user data

**Comment by dotrungkien3210** [comment]
Thanks @ShortRoundDev very much, i forgot that APIs
but my purpose is get raw gmail/phone when call generate success, not just the adv token and times
hope this feature will be implement in the future

**Comment by sunnywu** [comment]
Thanks for the message @dotrungkien3210. Are you a publisher or DSP or data provider? Currently only DSP would be able to decrypt a UID2 token to get the raw UID2 value (and then you re-compute the raw UID2 value of a gmail/phone to do the comparison if they match, as it's impossible to get the original gmail/phone from a raw UID2 value).

**Comment by sunnywu** [comment]
Hi @dotrungkien3210 I will close this issue for now but if you have any further feedback please reply and we can follow up. Thanks
